-- Clean up all data from tables
TRUNCATE TABLE applications CASCADE;
TRUNCATE TABLE activities CASCADE;
TRUNCATE TABLE opportunities CASCADE;
TRUNCATE TABLE profiles CASCADE;

-- Re-enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;